#!/usr/bin/env python3
"""Build inventory.yaml from a folder of inspection photos. No cropping.

Duplicates are sha256 (not the model). Each unique image is labelled by Vertex
Gemini with a Pydantic response_schema (structured output, not a JSON prompt).

    gcloud auth application-default login
    gcloud auth application-default set-quota-project linen-badge-507111-r6
    python cv/generate_inventory.py fixtures/fleet-vehicle-return/images \\
        --out /tmp/inventory.yaml
"""

from __future__ import annotations

import argparse
import hashlib
import json
import mimetypes
import os
import sys
import time
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from schema import ImageLabel
from taxonomy import LABEL_TASK

IMAGE_EXT = {".jpg", ".jpeg", ".png"}
PROJECT = os.environ.get("GOOGLE_CLOUD_PROJECT", "linen-badge-507111-r6")
LOCATION = os.environ.get("GOOGLE_CLOUD_LOCATION", "global")
MODEL = os.environ.get("CV_MODEL", "gemini-2.5-flash")


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 16), b""):
            h.update(chunk)
    return h.hexdigest()


def list_images(folder: Path) -> list[Path]:
    files = [p for p in folder.iterdir() if p.suffix.lower() in IMAGE_EXT and p.is_file()]
    return sorted(files, key=lambda p: p.name)


def collapse_duplicates(paths: list[Path]) -> tuple[list[Path], list[list[str]]]:
    by_hash: dict[str, list[Path]] = defaultdict(list)
    for p in paths:
        by_hash[sha256_file(p)].append(p)
    unique: list[Path] = []
    pairs: list[list[str]] = []
    for group in by_hash.values():
        group = sorted(group, key=lambda p: p.name)
        unique.append(group[0])
        if len(group) > 1:
            for extra in group[1:]:
                pairs.append([group[0].name, extra.name])
    unique.sort(key=lambda p: p.name)
    return unique, pairs


def observations_from(label: ImageLabel) -> dict:
    obs: dict = {}
    if label.odometer_km is not None:
        obs["odometer_km"] = label.odometer_km
    if label.registration:
        obs["registration"] = label.registration
    if label.seat_side:
        obs["seat_side"] = label.seat_side
    if label.diagonal:
        obs["diagonal"] = label.diagonal
    if label.pose_evidence:
        obs["pose_evidence"] = label.pose_evidence
    warnings = [w.model_dump() for w in label.warnings if w.text or w.meaning]
    if warnings:
        obs["warnings"] = warnings
    return obs


def dump_yaml(images: list[dict], pairs: list[list[str]]) -> str:
    lines = [
        "# Generated by cv/generate_inventory.py — Vertex Gemini + Pydantic schema.",
        "# Cropping is out of scope.",
        "",
        "images:",
    ]
    for img in images:
        lines.append(f'  - file: "{img["file"]}"')
        lines.append(f"    depicts: {img['depicts']}")
        if img.get("shot_from"):
            lines.append(f"    shot_from: {img['shot_from']}")
        if img.get("note"):
            note = img["note"].replace("\n", " ").strip()
            lines.append(f"    note: {json.dumps(note, ensure_ascii=False)}")
        obs = img.get("observations") or {}
        if obs:
            lines.append("    observations:")
            if obs.get("odometer_km") is not None:
                lines.append(f"      odometer_km: {obs['odometer_km']}")
            if obs.get("registration"):
                lines.append(f'      registration: "{obs["registration"]}"')
            if obs.get("seat_side"):
                lines.append(f"      seat_side: {obs['seat_side']}")
            if obs.get("diagonal"):
                lines.append(f"      diagonal: {obs['diagonal']}")
            if obs.get("pose_evidence"):
                lines.append(f"      pose_evidence: {json.dumps(obs['pose_evidence'], ensure_ascii=False)}")
            warnings = obs.get("warnings") or []
            if warnings:
                lines.append("      warnings:")
                for w in warnings:
                    lines.append(f'        - text: {json.dumps(w.get("text") or "", ensure_ascii=False)}')
                    if w.get("meaning"):
                        lines.append(f'          meaning: {json.dumps(w["meaning"], ensure_ascii=False)}')
        if img.get("exact_duplicate_of"):
            lines.append(f'    exact_duplicate_of: "{img["exact_duplicate_of"]}"')
    lines.append("")
    lines.append("exact_duplicate_pairs:")
    if not pairs:
        lines.append("  []")
    else:
        for a, b in pairs:
            lines.append(f'  - ["{a}", "{b}"]')
    lines.append("")
    return "\n".join(lines)


def label_to_row(label: ImageLabel, filename: str) -> dict:
    return {
        "file": filename,
        "depicts": label.depicts,
        "shot_from": label.shot_from,
        "note": label.note.strip(),
        "observations": observations_from(label),
    }


def label_image(client, path: Path) -> dict:
    from google.genai import types

    mime = mimetypes.guess_type(path.name)[0] or "image/jpeg"
    last_err: Exception | None = None
    for attempt in range(6):
        try:
            response = client.models.generate_content(
                model=MODEL,
                contents=[
                    types.Part.from_bytes(data=path.read_bytes(), mime_type=mime),
                    LABEL_TASK,
                ],
                config=types.GenerateContentConfig(
                    response_mime_type="application/json",
                    response_schema=ImageLabel,
                    automatic_function_calling=types.AutomaticFunctionCallingConfig(disable=True),
                ),
            )
            parsed = response.parsed
            if parsed is None:
                parsed = ImageLabel.model_validate_json(response.text or "{}")
            elif not isinstance(parsed, ImageLabel):
                parsed = ImageLabel.model_validate(parsed)
            return label_to_row(parsed, path.name)
        except Exception as e:
            last_err = e
            msg = str(e)
            if "429" in msg or "RESOURCE_EXHAUSTED" in msg:
                wait = 10 * (attempt + 1)
                print(f"  rate-limited, sleep {wait}s", flush=True)
                time.sleep(wait)
                continue
            raise
    raise last_err or RuntimeError("label failed")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("images", type=Path, help="folder of jpg/png")
    parser.add_argument("--out", type=Path, default=Path("inventory.generated.yaml"))
    args = parser.parse_args()

    from google import genai

    client = genai.Client(vertexai=True, project=PROJECT, location=LOCATION)
    print(f"Vertex project={PROJECT} location={LOCATION} model={MODEL}", flush=True)

    folder = args.images.resolve()
    all_files = list_images(folder)
    if not all_files:
        print(f"no images in {folder}", file=sys.stderr)
        return 2

    unique, pairs = collapse_duplicates(all_files)
    print(f"{len(all_files)} files, {len(unique)} unique, {len(pairs)} duplicate extras", flush=True)

    labelled: list[dict] = []
    for path in unique:
        print(f"label {path.name} ...", flush=True)
        row = label_image(client, path)
        time.sleep(1)
        extras = [b for a, b in pairs if a == path.name]
        if extras:
            row["exact_duplicate_of"] = extras[0]
        labelled.append(row)

    text = dump_yaml(labelled, pairs)
    args.out.write_text(text)
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
