#!/usr/bin/env python3
"""Build inventory.yaml from a folder of inspection photos. No cropping.

Duplicates are sha256 (not the model). Each unique image is labelled by a
Vertex Gemini model (ADC — no API keys; org policy forbids them).

    gcloud auth application-default login
    gcloud auth application-default set-quota-project linen-badge-507111-r6
    python cv/generate_inventory.py fixtures/fleet-vehicle-return/images \\
        --out /tmp/inventory.yaml
"""

from __future__ import annotations

import argparse
import hashlib
import json
import mimetypes
import os
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from taxonomy import DEPICTS, HEADLINER_SHOT_FROM, LABEL_GUIDE

IMAGE_EXT = {".jpg", ".jpeg", ".png"}
PROJECT = os.environ.get("GOOGLE_CLOUD_PROJECT", "linen-badge-507111-r6")
LOCATION = os.environ.get("GOOGLE_CLOUD_LOCATION", "global")
MODEL = os.environ.get("CV_MODEL", "gemini-2.5-flash")


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 16), b""):
            h.update(chunk)
    return h.hexdigest()


def list_images(folder: Path) -> list[Path]:
    files = [p for p in folder.iterdir() if p.suffix.lower() in IMAGE_EXT and p.is_file()]
    return sorted(files, key=lambda p: p.name)


def collapse_duplicates(paths: list[Path]) -> tuple[list[Path], list[list[str]]]:
    by_hash: dict[str, list[Path]] = defaultdict(list)
    for p in paths:
        by_hash[sha256_file(p)].append(p)
    unique: list[Path] = []
    pairs: list[list[str]] = []
    for group in by_hash.values():
        group = sorted(group, key=lambda p: p.name)
        unique.append(group[0])
        if len(group) > 1:
            for extra in group[1:]:
                pairs.append([group[0].name, extra.name])
    unique.sort(key=lambda p: p.name)
    return unique, pairs


def dump_yaml(images: list[dict], pairs: list[list[str]]) -> str:
    lines = [
        "# Generated by cv/generate_inventory.py — Vertex Gemini labels, sha256 dedupe.",
        "# Cropping is out of scope.",
        "",
        "images:",
    ]
    for img in images:
        lines.append(f'  - file: "{img["file"]}"')
        lines.append(f"    depicts: {img['depicts']}")
        if img.get("shot_from"):
            lines.append(f"    shot_from: {img['shot_from']}")
        if img.get("note"):
            note = img["note"].replace("\n", " ").strip()
            lines.append(f"    note: {json.dumps(note, ensure_ascii=False)}")
        if img.get("exact_duplicate_of"):
            lines.append(f'    exact_duplicate_of: "{img["exact_duplicate_of"]}"')
    lines.append("")
    lines.append("exact_duplicate_pairs:")
    if not pairs:
        lines.append("  []")
    else:
        for a, b in pairs:
            lines.append(f'  - ["{a}", "{b}"]')
    lines.append("")
    return "\n".join(lines)


def parse_label_json(text: str, name: str) -> dict:
    text = text.strip()
    if text.startswith("```"):
        text = text.strip("`")
        text = text.removeprefix("json").strip()
    data = json.loads(text)
    depicts = data.get("depicts")
    if depicts not in DEPICTS:
        raise ValueError(f"{name}: unknown depicts {depicts!r} raw={text[:200]!r}")
    shot = data.get("shot_from") or None
    if depicts == "headliner":
        if shot not in HEADLINER_SHOT_FROM:
            raise ValueError(f"{name}: headliner missing shot_from, got {shot!r}")
    else:
        shot = None
    return {
        "file": name,
        "depicts": depicts,
        "shot_from": shot,
        "note": (data.get("note") or "").strip(),
    }


def label_image(client, path: Path) -> dict:
    from google.genai import types

    mime = mimetypes.guess_type(path.name)[0] or "image/jpeg"
    prompt = f"""You label vehicle-return inspection photos.

Choose exactly one depicts value:
{", ".join(DEPICTS)}

{LABEL_GUIDE}

Return ONLY JSON, no markdown:
{{"depicts": "<one of the values>", "shot_from": null or "between_front_seats" or "beside_seat", "note": "<short English note>"}}

shot_from must be set if and only if depicts is headliner.
shot_from allowed: {", ".join(HEADLINER_SHOT_FROM)}
"""
    response = client.models.generate_content(
        model=MODEL,
        contents=[
            types.Part.from_bytes(data=path.read_bytes(), mime_type=mime),
            prompt,
        ],
        config=types.GenerateContentConfig(
            response_mime_type="application/json",
            automatic_function_calling=types.AutomaticFunctionCallingConfig(disable=True),
        ),
    )
    return parse_label_json(response.text or "", path.name)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("images", type=Path, help="folder of jpg/png")
    parser.add_argument("--out", type=Path, default=Path("inventory.generated.yaml"))
    args = parser.parse_args()

    from google import genai

    client = genai.Client(vertexai=True, project=PROJECT, location=LOCATION)
    print(f"Vertex project={PROJECT} location={LOCATION} model={MODEL}", flush=True)

    folder = args.images.resolve()
    all_files = list_images(folder)
    if not all_files:
        print(f"no images in {folder}", file=sys.stderr)
        return 2

    unique, pairs = collapse_duplicates(all_files)
    print(f"{len(all_files)} files, {len(unique)} unique, {len(pairs)} duplicate extras", flush=True)

    labelled: list[dict] = []
    for path in unique:
        print(f"label {path.name} ...", flush=True)
        row = label_image(client, path)
        extras = [b for a, b in pairs if a == path.name]
        if extras:
            row["exact_duplicate_of"] = extras[0]
        labelled.append(row)

    text = dump_yaml(labelled, pairs)
    args.out.write_text(text)
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
