#!/usr/bin/env python3
"""Build inventory.yaml from checklist + provided-image list + photos.

    python cv/generate_inventory.py fixtures/fleet-vehicle-return/images \\
        --requirements fixtures/fleet-vehicle-return/expected_requirements.yaml \\
        --manifest fixtures/fleet-vehicle-return/manifest.txt \\
        --out cv/inventory.generated.yaml
"""

from __future__ import annotations

import argparse
import hashlib
import json
import mimetypes
import os
import sys
import time
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from schema import ImageLabel, ManifestRequirement, ParsedManifest
from taxonomy import label_task

IMAGE_EXT = {".jpg", ".jpeg", ".png"}
PROJECT = os.environ.get("GOOGLE_CLOUD_PROJECT", "linen-badge-507111-r6")
LOCATION = os.environ.get("GOOGLE_CLOUD_LOCATION", "global")
MODEL = os.environ.get("CV_MODEL", "gemini-2.5-flash")


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 16), b""):
            h.update(chunk)
    return h.hexdigest()


def list_images(folder: Path) -> list[Path]:
    files = [p for p in folder.iterdir() if p.suffix.lower() in IMAGE_EXT and p.is_file()]
    return sorted(files, key=lambda p: p.name)


def collapse_duplicates(paths: list[Path]) -> tuple[list[Path], list[list[str]]]:
    by_hash: dict[str, list[Path]] = defaultdict(list)
    for p in paths:
        by_hash[sha256_file(p)].append(p)
    unique: list[Path] = []
    pairs: list[list[str]] = []
    for group in by_hash.values():
        group = sorted(group, key=lambda p: p.name)
        unique.append(group[0])
        if len(group) > 1:
            for extra in group[1:]:
                pairs.append([group[0].name, extra.name])
    unique.sort(key=lambda p: p.name)
    return unique, pairs


def vertex_call(client, contents, schema, *, retries: int = 6):
    from google.genai import types

    last_err: Exception | None = None
    for attempt in range(retries):
        try:
            response = client.models.generate_content(
                model=MODEL,
                contents=contents,
                config=types.GenerateContentConfig(
                    response_mime_type="application/json",
                    response_schema=schema,
                    automatic_function_calling=types.AutomaticFunctionCallingConfig(disable=True),
                ),
            )
            parsed = response.parsed
            if parsed is None:
                parsed = schema.model_validate_json(response.text or "{}")
            elif not isinstance(parsed, schema):
                parsed = schema.model_validate(parsed)
            return parsed
        except Exception as e:
            last_err = e
            msg = str(e)
            if "429" in msg or "RESOURCE_EXHAUSTED" in msg:
                wait = 10 * (attempt + 1)
                print(f"  rate-limited, sleep {wait}s", flush=True)
                time.sleep(wait)
                continue
            raise
    raise last_err or RuntimeError("vertex call failed")


def load_requirements_yaml(path: Path) -> ParsedManifest:
    import yaml

    doc = yaml.safe_load(path.read_text())
    reqs = []
    for row in doc.get("requirements") or []:
        constraint = None
        raw = row.get("constraint")
        if isinstance(raw, dict):
            constraint = raw.get("value") or raw.get("kind")
        elif isinstance(raw, str):
            constraint = raw
        text = row.get("text") or ""
        if not isinstance(text, str):
            text = str(text)
        reqs.append(
            ManifestRequirement(
                id=row["id"],
                text=text.strip(),
                source_span=row.get("source_span") or "",
                expected_count=int(row.get("expected_count") or 1),
                constraint=constraint,
            )
        )
    return ParsedManifest(
        expected_total_photos=doc.get("expected_total_photos"),
        requirements=reqs,
    )


def observations_from(label: ImageLabel) -> dict:
    obs: dict = {}
    if label.odometer_km is not None:
        obs["odometer_km"] = label.odometer_km
    if label.registration:
        obs["registration"] = label.registration
    if label.seat_side:
        obs["seat_side"] = label.seat_side
    if label.pose_evidence:
        obs["pose_evidence"] = label.pose_evidence
    if label.constraint_ok is not None:
        obs["constraint_ok"] = label.constraint_ok
    warnings = [w.model_dump() for w in label.warnings if w.text or w.meaning]
    if warnings:
        obs["warnings"] = warnings
    return obs


def dump_yaml(parsed: ParsedManifest, images: list[dict], pairs: list[list[str]]) -> str:
    lines = [
        "# Generated by cv/generate_inventory.py",
        "# Inputs: expected_requirements (checklist) + manifest (provided shots) + images.",
        "",
        "expected_requirements:",
    ]
    if parsed.expected_total_photos is not None:
        lines.append(f"  expected_total_photos: {parsed.expected_total_photos}")
    lines.append("  requirements:")
    for r in parsed.requirements:
        lines.append(f'    - id: {r.id}')
        lines.append(f"      text: {json.dumps(r.text, ensure_ascii=False)}")
        lines.append(f"      source_span: {json.dumps(r.source_span, ensure_ascii=False)}")
        lines.append(f"      expected_count: {r.expected_count}")
        if r.constraint:
            lines.append(f"      constraint: {json.dumps(r.constraint, ensure_ascii=False)}")
    lines.append("")
    lines.append("images:")
    for img in images:
        lines.append(f'  - file: "{img["file"]}"')
        ids = img.get("requirement_ids") or []
        lines.append(f"    requirement_ids: {json.dumps(ids)}")
        if img.get("note"):
            lines.append(f"    note: {json.dumps(img['note'].replace(chr(10), ' ').strip(), ensure_ascii=False)}")
        obs = img.get("observations") or {}
        if obs:
            lines.append("    observations:")
            if obs.get("constraint_ok") is not None:
                lines.append(f"      constraint_ok: {str(obs['constraint_ok']).lower()}")
            if obs.get("odometer_km") is not None:
                lines.append(f"      odometer_km: {obs['odometer_km']}")
            if obs.get("registration"):
                lines.append(f'      registration: "{obs["registration"]}"')
            if obs.get("seat_side"):
                lines.append(f"      seat_side: {obs['seat_side']}")
            if obs.get("pose_evidence"):
                lines.append(f"      pose_evidence: {json.dumps(obs['pose_evidence'], ensure_ascii=False)}")
            warnings = obs.get("warnings") or []
            if warnings:
                lines.append("      warnings:")
                for w in warnings:
                    lines.append(f'        - text: {json.dumps(w.get("text") or "", ensure_ascii=False)}')
                    if w.get("meaning"):
                        lines.append(f'          meaning: {json.dumps(w["meaning"], ensure_ascii=False)}')
        if img.get("exact_duplicate_of"):
            lines.append(f'    exact_duplicate_of: "{img["exact_duplicate_of"]}"')
    lines.append("")
    lines.append("exact_duplicate_pairs:")
    if not pairs:
        lines.append("  []")
    else:
        for a, b in pairs:
            lines.append(f'  - ["{a}", "{b}"]')
    lines.append("")
    return "\n".join(lines)


def label_image(client, path: Path, parsed: ParsedManifest, manifest_text: str) -> dict:
    from google.genai import types

    mime = mimetypes.guess_type(path.name)[0] or "image/jpeg"
    known = {r.id for r in parsed.requirements}
    label: ImageLabel = vertex_call(
        client,
        [
            types.Part.from_bytes(data=path.read_bytes(), mime_type=mime),
            label_task(parsed.requirements, manifest_text),
        ],
        ImageLabel,
    )
    ids = [i for i in label.requirement_ids if i in known]
    return {
        "file": path.name,
        "requirement_ids": ids,
        "note": label.note.strip(),
        "observations": observations_from(label),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("images", type=Path, help="folder of jpg/png")
    parser.add_argument(
        "--requirements",
        type=Path,
        required=True,
        help="expected_requirements.yaml — what to extract from the photos",
    )
    parser.add_argument(
        "--manifest",
        type=Path,
        required=True,
        help="manifest.txt — list of images the client says they provided",
    )
    parser.add_argument("--out", type=Path, default=Path("inventory.generated.yaml"))
    args = parser.parse_args()

    from google import genai

    client = genai.Client(vertexai=True, project=PROJECT, location=LOCATION)
    print(f"Vertex project={PROJECT} location={LOCATION} model={MODEL}", flush=True)

    parsed = load_requirements_yaml(args.requirements)
    manifest_text = args.manifest.read_text()
    print(f"checklist {len(parsed.requirements)} reqs from {args.requirements}", flush=True)
    print(f"provided-shot list {args.manifest}", flush=True)

    folder = args.images.resolve()
    all_files = list_images(folder)
    if not all_files:
        print(f"no images in {folder}", file=sys.stderr)
        return 2

    unique, pairs = collapse_duplicates(all_files)
    print(f"{len(all_files)} files, {len(unique)} unique, {len(pairs)} duplicate extras", flush=True)

    labelled: list[dict] = []
    for path in unique:
        print(f"label {path.name} ...", flush=True)
        row = label_image(client, path, parsed, manifest_text)
        time.sleep(1)
        extras = [b for a, b in pairs if a == path.name]
        if extras:
            row["exact_duplicate_of"] = extras[0]
        labelled.append(row)

    args.out.write_text(dump_yaml(parsed, labelled, pairs))
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
