steps:
  - name: gcr.io/cloud-builders/docker
    env:
      - DOCKER_BUILDKIT=1
    args:
      - build
      - -f
      - docker/email-service.Dockerfile
      - -t
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
substitutions:
  _IMAGE: europe-central2-docker.pkg.dev/linen-badge-507111-r6/app/email:v1
timeout: 1200s
